### PR TITLE
add comment for safety in windows

### PR DESCRIPTION
**Pull request by upsuper**
This changes `PollReadFd::inner` to an `unsafe fn` because this function itself is not safe.

And consequently there are several more `unsafe` keywords around, and I add comment trying to explain why the use of `unsafe` is safe.

### CODE REVIEW

**Comment by stbuehler** [comment]
This is an internal function, and I don't think it improves readability putting `unsafe` all over the place (that is why I made it a function in the first place).

**Comment by upsuper** [comment]
It's not about readability, it's about soundness guarantee. A function not marked `unsafe` should never cause undefined behavior, which is how Rust generally works.

**Comment by stbuehler** [comment]
I disagree.

The public API should be safe, but if you require it for internal functions, where do you stop?  Because someone else might ask me to mark bigger blocks as unsafe, because if the code before an `unsafe` block is broken the `unsafe` block might not be safe anymore... not going there, unless you can show the reference saying the compiler is allowed to break my code even for safe inputs.

I'm open to explicitly documenting the requirements for such calls to be safe (which is way more helpful than putting `unsafe {...}` blocks everywhere).

**Comment by upsuper** [comment]
Whenever you see an `unsafe` block, it should be apparent why this is safe **locally**, otherwise the function should be `unsafe` and its caller has the responsibility to prove it is using the function safely.

The `unsafe` here is not sound because it relies on remote code (which can be a function far away or even in a different file) to call it in the right context, which is not a good practice, and harder to audit.

**Comment by stbuehler** [comment]
For the record: this is gone now through the use of `Mutex`.

**Pull request closed without merging**
