### PR TITLE
Add an example of how to use the library to browse for services

### PR DESCRIPTION
**Pull request by Ryman**
I do wonder if perhaps it's better to have some kind of better handling of the metaquery within the library? (I haven't read enough on the topic to know if that's appropriate though)

### CODE REVIEW

**Comment by Ryman** [comment]
Appveyor failing with unrelated issue: 

> The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

**Comment by stbuehler** [comment]
I actually had some examples on my own, I should probably add them to the repo :)

It's probably gonna be a mix of your example and mine; I also had some timeout handling code.

**Comment by stbuehler** [comment]
Thanks for your input!

**Comment by stbuehler** [comment]
Regarding AppVeyor: I enabled AppVeyor for the project, and it seems they started trying to build even when `[.]appveyor.yml` is missing.  I disabled that now, as I still don't have a good way building for windows; I'd need a mdns.lib/.dll to link against (I was working on implementing the mdns IPC API in rust which would replace the need for that).

**Pull request closed without merging**
